<a href="https://colab.research.google.com/github/HarshESC/TalkData-Mobile-Demographics/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import warnings
warnings.filterwarnings('ignore')
from google.colab import drive 
drive.mount('/content/gdrive')
import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/"
%cd "/content/gdrive/My Drive/Final Capstone"

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import (
    Activation,
    Dropout,
    Flatten,
    Dense,
    BatchNormalization,
)
from tensorflow.keras import backend as K
from sklearn.metrics import classification_report


Mounted at /content/gdrive
/content/gdrive/My Drive/Final Capstone


In [2]:
master_df = pd.read_csv("master_clean_2.csv")
X = master_df.drop(columns=["num_group"])
y = master_df["num_group"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=13, stratify=y
)


In [3]:
X_test


event_id               app_id  ...  device_model_魅蓝metal  device_model_麦芒4
3972     331345 -1633912816187681087  ...                     0                 0
34708   3137225  4348659952760821294  ...                     0                 0
1279     144053 -8103714741965524240  ...                     0                 0
8021     663472 -1200607960388315089  ...                     0                 0
10225    913759    33792862810792679  ...                     0                 1
...         ...                  ...  ...                   ...               ...
34832   3148380 -9050100410106163077  ...                     0                 0
471       45155  7316250158002095415  ...                     0                 0
14095   1165984 -1073344577746533072  ...                     0                 0
23610   2117736  -974457023668610292  ...                     0                 0
12927   1077613 -7509752927626140732  ...                     0                 0

[7208 rows x 47 columns]

In [4]:
y_test


3972      5
34708     5
1279     10
8021      5
10225     5
         ..
34832     4
471       1
14095     5
23610     3
12927     5
Name: num_group, Length: 7208, dtype: int64

In [5]:
master_df["num_group"].value_counts()


5     11416
4      9521
3      5955
10     2862
9      2060
11     1697
1      1596
2       585
0       345
Name: num_group, dtype: int64

In [6]:
# Output_dim = 12 because there are 12 different age/gender groups
output_dim = 12


In [7]:
X_train_np = X_train.to_numpy()
X_test_np = X_test.to_numpy()
y_train = to_categorical(y_train, output_dim)
y_test = to_categorical(y_test, output_dim)


# 3 Layer RELU Model with ADAM Optimizer


In [8]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dense(12, activation="softmax"))


In [9]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])


In [10]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)


Epoch 1/20
226/226 [==============================] - 1s 2ms/step - loss: 48577789514743808.0000 - accuracy: 0.2977
Epoch 2/20
226/226 [==============================] - 1s 2ms/step - loss: 16006550690725888.0000 - accuracy: 0.3256
Epoch 3/20
226/226 [==============================] - 0s 2ms/step - loss: 14281255885471744.0000 - accuracy: 0.3309
Epoch 4/20
226/226 [==============================] - 1s 2ms/step - loss: 12010318771257344.0000 - accuracy: 0.3431
Epoch 5/20
226/226 [==============================] - 1s 2ms/step - loss: 11933172568686592.0000 - accuracy: 0.3414
Epoch 6/20
226/226 [==============================] - 1s 2ms/step - loss: 11963560536047616.0000 - accuracy: 0.3421
Epoch 7/20
226/226 [==============================] - 1s 2ms/step - loss: 10184119078092800.0000 - accuracy: 0.3468
Epoch 8/20
226/226 [==============================] - 0s 2ms/step - loss: 9654902871556096.0000 - accuracy: 0.3465
Epoch 9/20
226/226 [==============================] - 1s 2ms/step - loss:

In [11]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])


Test accuracy: 0.2866259813308716


In [12]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)


In [13]:
print("Classification Report:")
print()
print(classification_report(y_test_arg, y_pred_arg))

Classification Report:

              precision    recall  f1-score   support

           0       0.11      0.04      0.06        69
           1       0.40      0.35      0.37       319
           2       0.23      0.11      0.15       117
           3       0.26      0.20      0.22      1191
           4       0.34      0.35      0.35      1904
           5       0.44      0.36      0.39      2283
           9       0.25      0.11      0.15       412
          10       0.22      0.18      0.20       573
          11       0.05      0.23      0.09       340

    accuracy                           0.29      7208
   macro avg       0.26      0.21      0.22      7208
weighted avg       0.33      0.29      0.30      7208



# 3 Layer RELU Model with SGD Optimizer


In [14]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dense(12, activation="softmax"))


In [15]:
model.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])


In [16]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)


Epoch 1/20
226/226 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.0096
Epoch 2/20
226/226 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0096
Epoch 3/20
226/226 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0096
Epoch 4/20
226/226 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0096
Epoch 5/20
226/226 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0096
Epoch 6/20
226/226 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0096
Epoch 7/20
226/226 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0096
Epoch 8/20
226/226 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0096
Epoch 9/20
226/226 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0096
Epoch 10/20
226/226 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0096
Epoch 11/20
226/226 [========

In [17]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])


Test accuracy: 0.00957269687205553


In [18]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)


In [19]:
print("Classification Report:")
print()
print(classification_report(y_test_arg, y_pred_arg))

Classification Report:

              precision    recall  f1-score   support

           0       0.01      1.00      0.02        69
           1       0.00      0.00      0.00       319
           2       0.00      0.00      0.00       117
           3       0.00      0.00      0.00      1191
           4       0.00      0.00      0.00      1904
           5       0.00      0.00      0.00      2283
           9       0.00      0.00      0.00       412
          10       0.00      0.00      0.00       573
          11       0.00      0.00      0.00       340

    accuracy                           0.01      7208
   macro avg       0.00      0.11      0.00      7208
weighted avg       0.00      0.01      0.00      7208



# 3 Layer TANH Model with ADAM Optimizer

In [20]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="tanh"))
model.add(Dense(64, activation="tanh"))
model.add(Dense(12, activation="softmax"))


In [21]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])


In [22]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)


Epoch 1/20
226/226 [==============================] - 1s 2ms/step - loss: 1.9270 - accuracy: 0.3696
Epoch 2/20
226/226 [==============================] - 1s 2ms/step - loss: 1.4848 - accuracy: 0.4487
Epoch 3/20
226/226 [==============================] - 0s 2ms/step - loss: 1.3992 - accuracy: 0.4680
Epoch 4/20
226/226 [==============================] - 0s 2ms/step - loss: 1.3528 - accuracy: 0.4857
Epoch 5/20
226/226 [==============================] - 1s 2ms/step - loss: 1.3177 - accuracy: 0.5020
Epoch 6/20
226/226 [==============================] - 1s 2ms/step - loss: 1.2878 - accuracy: 0.5104
Epoch 7/20
226/226 [==============================] - 0s 2ms/step - loss: 1.2620 - accuracy: 0.5208
Epoch 8/20
226/226 [==============================] - 0s 2ms/step - loss: 1.2443 - accuracy: 0.5256
Epoch 9/20
226/226 [==============================] - 1s 2ms/step - loss: 1.2224 - accuracy: 0.5339
Epoch 10/20
226/226 [==============================] - 0s 2ms/step - loss: 1.2080 - accuracy: 0.5358

In [23]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])


Test accuracy: 0.5529966950416565


In [24]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)


In [26]:
print("Classification Report:")
print()
print(classification_report(y_test_arg , y_pred_arg))

Classification Report:

              precision    recall  f1-score   support

           0       0.50      0.04      0.08        69
           1       0.88      0.28      0.42       319
           2       0.52      0.15      0.23       117
           3       0.56      0.57      0.56      1191
           4       0.53      0.58      0.55      1904
           5       0.53      0.72      0.61      2283
           9       0.53      0.33      0.41       412
          10       0.81      0.41      0.54       573
          11       0.51      0.24      0.32       340

    accuracy                           0.55      7208
   macro avg       0.60      0.37      0.41      7208
weighted avg       0.57      0.55      0.54      7208



# 3 Layer TANH Model with SGD Optimizer

In [27]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="tanh"))
model.add(Dense(64, activation="tanh"))
model.add(Dense(12, activation="softmax"))


In [28]:
model.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])


In [29]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)


Epoch 1/20
226/226 [==============================] - 1s 2ms/step - loss: 2.2060 - accuracy: 0.2774
Epoch 2/20
226/226 [==============================] - 0s 2ms/step - loss: 1.8249 - accuracy: 0.3790
Epoch 3/20
226/226 [==============================] - 0s 2ms/step - loss: 1.6737 - accuracy: 0.3983
Epoch 4/20
226/226 [==============================] - 0s 2ms/step - loss: 1.6055 - accuracy: 0.4119
Epoch 5/20
226/226 [==============================] - 0s 2ms/step - loss: 1.5665 - accuracy: 0.4267
Epoch 6/20
226/226 [==============================] - 0s 2ms/step - loss: 1.5384 - accuracy: 0.4336
Epoch 7/20
226/226 [==============================] - 0s 2ms/step - loss: 1.5154 - accuracy: 0.4429
Epoch 8/20
226/226 [==============================] - 0s 2ms/step - loss: 1.4967 - accuracy: 0.4499
Epoch 9/20
226/226 [==============================] - 0s 2ms/step - loss: 1.4799 - accuracy: 0.4551
Epoch 10/20
226/226 [==============================] - 0s 2ms/step - loss: 1.4651 - accuracy: 0.4590

In [30]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])


Test accuracy: 0.4816870093345642


In [31]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)


In [32]:
res = tf.math.confusion_matrix(y_test_arg, y_pred_arg)
print(res)


tf.Tensor(
[[   0    0    0   33    3   33    0    0    0    0    0    0]
 [   0   64    0   63   65  122    0    0    0    0    5    0]
 [   0    0    0   80    8   29    0    0    0    0    0    0]
 [   0    0    0  881   94  201    0    0    0    6    9    0]
 [   0    0    0  402  922  542    0    0    0    4   33    1]
 [   0   44    0  355  510 1275    0    0    0    6   93    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0   48  214   66    0    0    0   69   15    0]
 [   0    0    0   28  195   89    0    0    0    0  261    0]
 [   0    0    0   70  118  146    0    0    0    5    1    0]], shape=(12, 12), dtype=int32)


In [33]:
print("Classification Report:")
print()
print(classification_report(y_test_arg, y_pred_arg))

Classification Report:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        69
           1       0.59      0.20      0.30       319
           2       0.00      0.00      0.00       117
           3       0.45      0.74      0.56      1191
           4       0.43      0.48      0.46      1904
           5       0.51      0.56      0.53      2283
           9       0.77      0.17      0.27       412
          10       0.63      0.46      0.53       573
          11       0.00      0.00      0.00       340

    accuracy                           0.48      7208
   macro avg       0.38      0.29      0.29      7208
weighted avg       0.47      0.48      0.45      7208



# 3 Layer Sigmoid with ADAM Optimizer

In [34]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="sigmoid"))
model.add(Dense(64, activation="sigmoid"))
model.add(Dense(12, activation="softmax"))


In [35]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])


In [36]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)


Epoch 1/20
226/226 [==============================] - 1s 2ms/step - loss: 1.6871 - accuracy: 0.3576
Epoch 2/20
226/226 [==============================] - 1s 2ms/step - loss: 1.5856 - accuracy: 0.3815
Epoch 3/20
226/226 [==============================] - 1s 2ms/step - loss: 1.5450 - accuracy: 0.3957
Epoch 4/20
226/226 [==============================] - 0s 2ms/step - loss: 1.5149 - accuracy: 0.4039
Epoch 5/20
226/226 [==============================] - 0s 2ms/step - loss: 1.4931 - accuracy: 0.4169
Epoch 6/20
226/226 [==============================] - 1s 2ms/step - loss: 1.4732 - accuracy: 0.4239
Epoch 7/20
226/226 [==============================] - 0s 2ms/step - loss: 1.4567 - accuracy: 0.4369
Epoch 8/20
226/226 [==============================] - 0s 2ms/step - loss: 1.4411 - accuracy: 0.4425
Epoch 9/20
226/226 [==============================] - 1s 2ms/step - loss: 1.4272 - accuracy: 0.4485
Epoch 10/20
226/226 [==============================] - 0s 2ms/step - loss: 1.4156 - accuracy: 0.4535

In [37]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])


Test accuracy: 0.4944505989551544


In [38]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)


In [39]:
print("Classification Report:")
print()
print(classification_report(y_test_arg, y_pred_arg))

Classification Report:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        69
           1       0.53      0.16      0.24       319
           2       0.00      0.00      0.00       117
           3       0.42      0.77      0.54      1191
           4       0.47      0.43      0.45      1904
           5       0.53      0.63      0.58      2283
           9       0.70      0.22      0.33       412
          10       0.65      0.38      0.48       573
          11       0.84      0.08      0.15       340

    accuracy                           0.49      7208
   macro avg       0.46      0.30      0.31      7208
weighted avg       0.52      0.49      0.47      7208



# 3 Layer Sigmoid with SGD Optimizer

In [40]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="sigmoid"))
model.add(Dense(64, activation="sigmoid"))
model.add(Dense(12, activation="softmax"))


In [41]:
model.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy"])


In [42]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1)


Epoch 1/20
226/226 [==============================] - 1s 2ms/step - loss: 1.8837 - accuracy: 0.2963
Epoch 2/20
226/226 [==============================] - 0s 2ms/step - loss: 1.7262 - accuracy: 0.3355
Epoch 3/20
226/226 [==============================] - 0s 2ms/step - loss: 1.6952 - accuracy: 0.3496
Epoch 4/20
226/226 [==============================] - 0s 2ms/step - loss: 1.6771 - accuracy: 0.3538
Epoch 5/20
226/226 [==============================] - 0s 2ms/step - loss: 1.6653 - accuracy: 0.3550
Epoch 6/20
226/226 [==============================] - 0s 2ms/step - loss: 1.6566 - accuracy: 0.3581
Epoch 7/20
226/226 [==============================] - 0s 2ms/step - loss: 1.6501 - accuracy: 0.3579
Epoch 8/20
226/226 [==============================] - 0s 2ms/step - loss: 1.6447 - accuracy: 0.3585
Epoch 9/20
226/226 [==============================] - 0s 2ms/step - loss: 1.6401 - accuracy: 0.3585
Epoch 10/20
226/226 [==============================] - 0s 2ms/step - loss: 1.6361 - accuracy: 0.3604

In [43]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])


Test accuracy: 0.36750832200050354


In [44]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)


In [45]:
print("Classification Report:")
print()
print(classification_report(y_test_arg, y_pred_arg))

Classification Report:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        69
           1       0.00      0.00      0.00       319
           2       0.00      0.00      0.00       117
           3       0.38      0.79      0.51      1191
           4       0.32      0.08      0.13      1904
           5       0.37      0.68      0.48      2283
           9       0.00      0.00      0.00       412
          10       0.00      0.00      0.00       573
          11       0.00      0.00      0.00       340

    accuracy                           0.37      7208
   macro avg       0.12      0.17      0.12      7208
weighted avg       0.26      0.37      0.27      7208



# 3 Layer RELU with ADAM Optimizer Smaller Batch Size and More Epochs

In [46]:
model = Sequential()
model.add(Dense(128, input_dim=X_train_np.shape[1], activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dense(12, activation="softmax"))


In [47]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])


In [48]:
model.fit(X_train, y_train, batch_size=64, epochs=100, verbose=1)


Epoch 1/100
451/451 [==============================] - 1s 2ms/step - loss: 53313832772173824.0000 - accuracy: 0.2986
Epoch 2/100
451/451 [==============================] - 1s 2ms/step - loss: 18097467471953920.0000 - accuracy: 0.3289
Epoch 3/100
451/451 [==============================] - 1s 2ms/step - loss: 16219831250452480.0000 - accuracy: 0.3342
Epoch 4/100
451/451 [==============================] - 1s 2ms/step - loss: 13094014181965824.0000 - accuracy: 0.3390
Epoch 5/100
451/451 [==============================] - 1s 2ms/step - loss: 11609833472000000.0000 - accuracy: 0.3435
Epoch 6/100
451/451 [==============================] - 1s 2ms/step - loss: 9591701354053632.0000 - accuracy: 0.3415
Epoch 7/100
451/451 [==============================] - 1s 2ms/step - loss: 8190737782931456.0000 - accuracy: 0.3112
Epoch 8/100
451/451 [==============================] - 1s 2ms/step - loss: 6315950735360000.0000 - accuracy: 0.3313
Epoch 9/100
451/451 [==============================] - 1s 2ms/step 

In [49]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test accuracy:", score[1])


Test accuracy: 0.3171476125717163


In [50]:
y_pred = model.predict(X_test)
y_test_arg = tf.argmax(y_test, 1)
y_pred_arg = tf.argmax(y_pred, 1)


In [51]:
print("Classification Report:")
print()
print(classification_report(y_test_arg, y_pred_arg))

Classification Report:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        69
           1       0.00      0.00      0.00       319
           2       0.00      0.00      0.00       117
           3       1.00      0.00      0.01      1191
           4       0.00      0.00      0.00      1904
           5       0.32      1.00      0.48      2283
           9       0.00      0.00      0.00       412
          10       0.00      0.00      0.00       573
          11       0.00      0.00      0.00       340

    accuracy                           0.32      7208
   macro avg       0.15      0.11      0.05      7208
weighted avg       0.27      0.32      0.15      7208

